[build]
  publish = "."
  command = ""

# Redirect root and pretty URLs to their respective HTML files
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/leaderboard"
  to = "/leaderboard.html"
  status = 200

[[redirects]]
  from = "/profile"
  to = "/profile.html"
  status = 200

[[redirects]]
  from = "/settings"
  to = "/settings.html"
  status = 200

[[redirects]]
  from = "/invite"
  to = "/invite.html"
  status = 200

# Optional: redirect /signup to index if you're using ?ref=
[[redirects]]
  from = "/signup"
  to = "/index.html"
  status = 200
